name: stor565
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - comm=0.2.3
  - cpython=3.14.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.0
  - python_abi=3.14
  - pyzmq=27.1.0
  - readline=8.3
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.11.0
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - dill==0.4.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.5.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.72.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.5
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - pytorch-ignite==0.5.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - setuptools==80.9.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xgboost==3.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
